version: '3.7'

networks:
  laravel:

# for local development
services:
  quasar:
    build:
      context: dockerfiles
      target: 'develop-stage'
    ports:
    - '9000:9000'
    volumes:
    - './src:/app'
    command: /bin/sh -c "npm i && npm run dev"
    networks:
      - laravel
      
  npm:
    image: node:current-alpine
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /app
    networks:
      - laravel

